### ISSUE TITLE
vjkit DateUtil.setMonths改进

### ISSUE THREAD

**Issue by KnightOfWind** [vipshop/vjtools#102]
一般符合大习惯的月份范围是：1-12，Java8中LocalDate和LocalDateTime的getMonthValue的返回值也是这个范围，这样更容易理解，而且也无需再做一次转换，即使切换到新的API也不会付出额外的抓换成本(主要是使用习惯问题)

**Comment by calvin1978** [comment]
谢谢，vjkit的真正用户一枚：）
