### ISSUE TITLE
什么样的授权能将此作为我公司的代码规范手册？

### ISSUE THREAD

**Issue by javamonkey** [vipshop/vjtools#112]
这个开发手册是我见过最实用的java开发手册，想作为公司的开发手册的基础，增加一些其他代码规范。
我需要有什么样的授权？

**Comment by calvin1978** [comment]
随便弄啊，找地方声明一下出处就好。 我们这个也是从阿里巴巴为蓝本改的，在开头声明一下版权就行

**Comment by javamonkey** [comment]
好的，谢谢
