### ISSUE TITLE
下载vjtop后如何使用呀？？？

### ISSUE THREAD

**Issue by ytrlmy521** [vipshop/vjtools#118]
介绍就说给一句 要使用相通过的JDK 版本 和用户 ，我下载后进入vjtop 目录 执行脚本后无法使用

**Comment by cmonkey** [comment]
你可以这样
jps -ml 可以得到你电脑上的java  进程信息
执行vjtop.sh PID

 example: 
jps -ml                                                             
17010 org.jetbrains.idea.maven.server.RemoteMavenServer
17795 sun.tools.jps.Jps -ml
3684 com.intellij.idea.Main

./vjtop.sh 17010

**Comment by ytrlmy521** [comment]
嗯嗯  好的  可能是我的 使用用户不一致问题 提示 要配置 JAVA__HOME 谢谢你
