### ISSUE TITLE
vjtop怎么查哪个class频繁创建线程使用完后，没有释放？

### ISSUE THREAD

**Issue by lqclester** [vipshop/vjtools#132]
已用jstack定位到大量wating线程没释放，导致tomcat down掉。

**Comment by GourdErwa** [comment]
> 已用jstack定位到大量wating线程没释放，导致tomcat down掉。

推荐手动创建线程池，这样可以定位到线程使用情况。
如果是使用开源内容线程池，寻找是否 IO 未正确关闭。

**Comment by calvin1978** [comment]
这个时候用greys 或 btrace更适合了。
