### ISSUE TITLE
libsysconfcpus限定CPU核数小于2导致的JVM死锁问题询问

### ISSUE THREAD

**Issue by 00jy116** [vipshop/vjtools#145]
TO @calvin1978 
morning

我们环境采用libsysconfcpus限定CPU核数为1的场景下，发生了死锁，修正为2之后情况解决，看到唯品会也遇到了相同的问题，我们一直在分析这块的原因，但当前还不清楚，所以想问一下，是由于什么原因导致了死锁，是单纯使用了libsysconfcpus.so这个导致的，还是说JVM对cpu核数存在某些要求？

以上

**Comment by 00jy116** [comment]
@calvin1978 
白衣：
是不是因为java -server方式最基础就是需要2core的原因？：
https://docs.oracle.com/javase/1.5.0/docs/guide/vm/server-class.html

**Comment by calvin1978** [comment]
是的呀
