### ISSUE TITLE
./vjtop.sh -h 启动时找不到 main class

### ISSUE THREAD

**Issue by Neo0** [vipshop/vjtools#146]
Error: Could not find or load main class com.vip.vjtools.vjtop.VJTop

**Comment by calvin1978** [comment]
哪个版本？

**Comment by manbuyun** [comment]
直接git clone，然后执行vjtop.sh pid。就是上面的异常了

**Comment by manbuyun** [comment]
应该是需要编译成jar吧，没看到vjtop.jar

**Comment by calvin1978** [comment]
是啊，兄弟没编译吧
