### ISSUE TITLE
destionationList单词拼写错误应该为destinationList

### ISSUE THREAD

**Issue by portlet-z** [vipshop/vjtools#151]
https://github.com/vipshop/vjtools/blob/6119dd30660df386b2d4d71501e579d1901a539d/vjkit/src/main/java/com/vip/vjtools/vjkit/mapper/BeanMapper.java#L43

**Comment by calvin1978** [comment]
谢谢认真的拼写检查员

**Comment by calvin1978** [comment]
谢谢认真的拼写检查员
