### ISSUE TITLE
JSON.pom/btoa()

### ISSUE THREAD

**Issue by chcdggrs** [vipshop/vjtools#30]
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>1.5-20090211</version>
</dependency>

**Comment by calvin1978** [comment]
hello, robot

**Comment by chcdggrs** [comment]
<div class="w3-container w3-teal">
  <h1>My Header</h1>
</div>

<img src="img_car.jpg" alt="Car">

<div class="w3-container">
  <p>A car is a wheeled, self-powered motor vehicle used for transportation.</p>
</div>

<div class="w3-container w3-teal">
  <p>My Footer</p>
</div>
