### ISSUE TITLE
option to dump old generation only?

### ISSUE THREAD

**Issue by ronyongxian** [vipshop/vjtools#32]
heap is bigger than 8G normally and takes long time&big disk to dump a whole one, expect an option to dump old generation only.
best wish!

**Comment by calvin1978** [comment]
vjmap -old pid, see the readme for detail

**Comment by ronyongxian** [comment]
i mean "jmap -dump:format=b" but not "jmap -histo:live"

**Comment by calvin1978** [comment]
sorry we can't do that...臣妾办不到啊。
