### ISSUE TITLE
vjtop如何实时交互

### ISSUE THREAD

**Issue by 191302041** [vipshop/vjtools#42]
![image](https://user-images.githubusercontent.com/9527011/41632441-8a90f484-746c-11e8-8bc2-339ffb33e315.png)
我想看繁忙的xiancheng线程在干神马 但是输入t或者m没有任何反应啊

**Comment by calvin1978** [comment]
clone snapshot编译一下

**Comment by calvin1978** [comment]
1.0.1也在发布中了，稍等一下。
