### ISSUE TITLE
希望可以在开发规范之外，分享一下关于前后端规范相关的内容

### ISSUE THREAD

**Issue by whyalwaysmea** [vipshop/vjtools#46]
从该项目中获取了很多开发上的规范，但是对于经验不那么丰富的人而言，前后端规范方面也是比较欠缺的。
不知道项目组是否有计划进行前后端规范的整理以及开源发布之类？
谢谢

**Comment by calvin1978** [comment]
这个项目主要针对java底层的东西，暂时先不扩展了。
