### ISSUE TITLE
[vjtop] 进一步改善 vjtop 的交互式体验

### ISSUE THREAD

**Issue by RobinGG** [vipshop/vjtools#47]
Hi Team,
我很喜欢 vjtop 最新添加的交互式操作，这让 vjtop 更加贴近 top 命令
不过我感觉在输入指令后还要按回车实在不够“Geek”
我在网上搜索以后，找到了下面这篇博客提到了可以实现更加贴近 top 的命令输入方式：
[Non blocking console input in Python and Java](https://www.darkcoding.net/software/non-blocking-console-io-is-not-possible/)
不过博客中提到的方法只适用于 Linux，Windows 需要引入额外的包
不知道 vjtools team 有没有兴趣研究一下

**Comment by calvin1978** [comment]
比较麻烦，先不做了，不是主要需求
