### ISSUE TITLE
关于 Orika 的潜在性 bug

### ISSUE THREAD

**Issue by drtrang** [vipshop/vjtools#5]
白衣大神，看 vjkit 的时候还在想出于什么考虑选用了用 Dozer，后来在 [BeanMapper](https://github.com/vipshop/vjtools/blob/master/vjkit/src/main/java/com/vip/vjtools/vjkit/reflect/BeanMapper.java#L16) 的注释看到了这句话：
> orika性能更好，也不需要Getter函数与无参构造函数，但有潜在bug还没在社区版修复

请问是啥 bug？我目前正在使用 Orika，并且基于 Orika 封装了一个工具 [Copiers](https://github.com/drtrang/Copiers)，想看下对我有没有影响。

**Comment by calvin1978** [comment]
这个bug说起来挺长的，简单说就是如果应用启动时有很多流量进来的话，有一定几率造成复制属性时复制成Null。

详情要呼叫个内部修复这个bug的同学出来解答。

**Comment by drtrang** [comment]
那就等我遇到再说吧，心里先有个底 😂

**Comment by calvin1978** [comment]
我们发布应用时遇到过不止一次了，才下定决心把bug挖出来。

**Comment by drtrang** [comment]
还不知道 Orika 这个强大的工具之前用的是 [EasyMapper](https://github.com/neoremind/easy-mapper)，后来偶然发现这个是参考 Orika 开发的才开始替换成 Orika。
之前用 EasyMapper 的时候一直有一个问题，Tomcat 启动的时候映射关系注册失败，导致后续的所有拷贝全部报错，而且是偶发的。后续经过无数次尝试仍然没有解决这个问题，至今也不清楚原因……
白衣大神看下这个 ISSUE 是类似的场景吗？https://github.com/neoremind/easy-mapper/issues/8

**Comment by smatiger** [comment]
@calvin1978    "有一定几率造成复制属性时复制成Null"  我也遇到了这个问题，请教一下现在知道原因是什么了吗？  有什么办法可以解决这个问题吗？  我使用版本的是：orika-core-1.4.2.jar
